name: Build and Deploy Docs (MkDocs + Doxygen)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ›  Install Dependencies (Doxygen + Python)
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz
          pip install mkdocs mkdocs-material
          pip install kconfiglib

      - name: ğŸ“š Generate Doxygen Documentation
        run: |
          doxygen Doxyfile
          mkdir -p docs/api
          cp -r docs_output/html/* docs/api/

      - name: ğŸ“š Generate Kconfig md
        run: python scripts/gen_kconfig_md.py zephyr/Kconfig --output docs/kconfig.md

      - name: ğŸ— Build MkDocs Site
        run: mkdocs build

      - name: ğŸš€ Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site